# A cautionary tale of ground state energy calculation

When calculating the ground state energy of an electronic structure Hamiltonian, some care should be exercised. Converting the Hamiltonian to a sparse matrix and finding the least eigenvalue will not always be the _true_ ground state with respect to the system it represents, since the diagonalization scheme used may not inherently observe any symmetries present in the underlying physical system.

Consider the following $H_3^+$ example, consisting of 2 electrons in 6 spin-orbitals...

In [258]:
from symmer.chemistry import MoleculeBuilder
from symmer.symplectic import array_to_QuantumState
from symmer.projection import QubitTapering

basis='sto-3g'
charge=+1
geometry =[
    ("H", [0., 0.558243000, 0.]),
    ("H", [0.483452000, -0.279121000, 0.]),
    ("H", [-0.483452000, -0.279121000, 0.])
]
molecule = MoleculeBuilder(geometry=geometry, charge=charge, basis=basis, spin=0, run_fci=True, print_info=True)

Molecule geometry:
H	0.0	0.558243	0.0
H	0.483452	-0.279121	0.0
H	-0.483452	-0.279121	0.0

HF converged?   True
CCSD converged? True
FCI converged?  True

HF energy:   -1.2468600063384467
MP2 energy:  -1.2658602663569571
CCSD energy: -1.2741446169583148
FCI energy:  -1.2741444671239888


Number of qubits: 6


Naively computing the ground state energy by taking the smallest eigenvalue of the Hamiltonian does not match the FCI energy:

In [283]:
from symmer.chemistry import MoleculeBuilder
from symmer.symplectic import array_to_QuantumState

basis='sto-3g'
charge=0
# geometry =[
#     ("H", [0., 0.558243000, 0.]),
#     ("H", [0.483452000, -0.279121000, 0.]),
# #     ("H", [0.483452000, -0.279121000, 1.]),
# #     ("H", [-0.483452000, -0.279121000, 0.])
# ]

geometry =[
    ("H", [0., 0., 0.]),
    ("H", [0., 0., 0.74]),
]
molecule = MoleculeBuilder(geometry=geometry, charge=charge, basis=basis, spin=0, run_fci=True, print_info=True)

Molecule geometry:
H	0.0	0.0	0.0
H	0.0	0.0	0.74

HF converged?   True
CCSD converged? True
FCI converged?  True

HF energy:   -1.1167593073964255
MP2 energy:  -1.1298973809859585
CCSD energy: -1.13728399861044
FCI energy:  -1.1372838344885028


Number of qubits: 4


In [284]:
from symmer.utils import exact_gs_energy

gs_nrg, gs_vec = exact_gs_energy(molecule.H_q.to_sparse_matrix)

print(f'Least eigenvalue = {gs_nrg} | FCI error = {gs_nrg - molecule.fci_energy}')

Least eigenvalue = -1.1372838344885017 | FCI error = 1.1102230246251565e-15


What has gone wrong here? Taking a look at the corresponding eigenvector, we see the identified state actually contains 3 particles, whereas the underlying system only contains 2:

In [285]:
psi = array_to_QuantumState(gs_vec).cleanup(zero_threshold=1e-5)
print(f'Eigenvector with eigenvalue {gs_nrg}:\n')
print(psi)

Eigenvector with eigenvalue -1.1372838344885017:

 0.113+0.000j |0011> +
-0.994+0.000j |1100>


To counter this issue, we instead need to select the least eigenvalue that contains the _correct_ number of particles. This is implemented in `symmer.chem.exact_gs_state`

In [286]:
from symmer.chemistry import exact_gs_energy

gs_nrg, gs_vec = exact_gs_energy(molecule.H_q.to_sparse_matrix, n_particles=2)
psi = array_to_QuantumState(gs_vec).cleanup(zero_threshold=1e-5)

print(f'Least eigenvalue = {gs_nrg} | FCI error = {gs_nrg - molecule.fci_energy}\n')
print(f'Eigenvector with eigenvalue {gs_nrg}:\n')
print(psi)

Least eigenvalue = -1.1372838344885017 | FCI error = 1.1102230246251565e-15

Eigenvector with eigenvalue -1.1372838344885017:

 0.113+0.000j |0011> +
-0.994+0.000j |1100>


Success! We have now recovered the true ground state by enforcing that only solutions with the correct number of particles are considered. Note however it is possible that no solution is identified at first - in this case, increase the `n_eigs` parameter in `symmer.chem.exact_gs_state` to increase the search space.

In [287]:
molecule.H_q

-0.097+0.000j IIII +
 0.171+0.000j ZIII +
 0.171+0.000j IZII +
-0.223+0.000j IIZI +
-0.223+0.000j IIIZ +
 0.169+0.000j ZZII +
 0.045+0.000j YXXY +
-0.045+0.000j YYXX +
-0.045+0.000j XXYY +
 0.045+0.000j XYYX +
 0.121+0.000j ZIZI +
 0.166+0.000j ZIIZ +
 0.166+0.000j IZZI +
 0.121+0.000j IZIZ +
 0.174+0.000j IIZZ

In [265]:
taper_hamiltonian = QubitTapering(molecule.H_q)

print(f'We are able to taper {taper_hamiltonian.n_taper} qubits from the Hamiltonian.\n')
print('The symmetry generators are\n')
print(taper_hamiltonian.symmetry_generators)
# print('\nand may be rotated onto the single-qubit Pauli operators\n')
# print(taper_hamiltonian.stabilizers.rotate_onto_single_qubit_paulis())
# print('\nvia a sequence of rotations e^{i pi/4 R} where\n')
# for index, (rot, angle) in enumerate(taper_hamiltonian.stabilizers.stabilizer_rotations):
#     print(f'R_{index} = {rot}')

We are able to taper 3 qubits from the Hamiltonian.

The symmetry generators are

 1 ZIIZ 
 1 IZIZ 
 1 IIZZ


In [280]:
from openfermion import FermionOperator
import numpy as np

def parity_operators(N_qubits):
    """
    note order is assumed to be spin up, spin down, spin up, spin down ... etc
    
    each op is built as product of parities of individual sites!
    
    https://arxiv.org/pdf/1008.4346.pdf
    """
    
    parity_up = FermionOperator('', 1)
    for spin_up_ind in np.arange(0,N_qubits, 2):
        parity_up*= FermionOperator('', 1) - 2*FermionOperator(f'{spin_up_ind}^ {spin_up_ind}', 1)#
    
    parity_down = FermionOperator('',1)
    for spin_down_ind in  np.arange(1,N_qubits, 2):
        parity_down*= FermionOperator('', 1) - 2*FermionOperator(f'{spin_down_ind}^ {spin_down_ind}', 1)
    
    return parity_up, parity_down

In [281]:
up_parity, down_parity = parity_operators(len(molecule.hf_array))

In [282]:
print(jordan_wigner(up_parity))
print()
print(jordan_wigner(down_parity))

(1+0j) [Z0 Z2]

(1+0j) [Z1 Z3]


In [ ]:
ZIZI (up)
IZIZ (down)
###


1 ZIIZ (a)
1 IZIZ (b)
1 IIZZ (c)


down == b

up == (a).(c)


In [256]:
print(bravyi_kitaev(up_parity))
print()
print(bravyi_kitaev(down_parity))

(1+0j) [Z0 Z2 Z4 Z6]

(1+0j) [Z0 Z2 Z4 Z6 Z7]


In [278]:
taper_hamiltonian.stabilizers.update_sector(molecule.hf_array)

print(taper_hamiltonian.symmetry_generators)

-1 ZIIZ 
-1 IZIZ 
 1 IIZZ


In [279]:
# molecule.H

In [294]:
molecule.hf_array

array([1, 1, 0, 0])

In [273]:
HF_state = np.eye(2**molecule.n_qubits)[int(''.join(map(str, molecule.hf_array.tolist())), 2), :]

In [274]:
from functools import reduce
test = [np.array([[0],[1]]) if bit==1 else np.array([[1],[0]]) for bit in molecule.hf_array]
test_state = reduce(np.kron, test)

np.allclose(test_state.reshape([-1]), HF_state.reshape([-1]))

True

In [275]:
from openfermion import get_sparse_operator

HF_state.conj().T @get_sparse_operator(up_parity, n_qubits=molecule.n_qubits) @ HF_state

(-1+0j)

In [276]:
HF_state.conj().T @get_sparse_operator(down_parity, n_qubits=molecule.n_qubits) @ HF_state

(-1+0j)

https://arxiv.org/pdf/1007.0586.pdf

parity operator for site $i$ is:

$$(-1)^{n_{i}}$$

aka -1 to the power of number of particles on site $i$

https://arxiv.org/pdf/1008.4346.pdf

In [137]:
n_0 =  FermionOperator(f'{0}^ {0}', 1)
n_1 =  FermionOperator(f'{1}^ {1}', 1)
n_2 =  FermionOperator(f'{2}^ {2}', 1)
n_3 =  FermionOperator(f'{3}^ {3}', 1)
ni_list = [n_0, n_1, n_2, n_3]

In [138]:
from openfermion import jordan_wigner, bravyi_kitaev

j0,j1,j2,j3 = [jordan_wigner(n) for n in ni_list]

q_list = [j0,j1,j2,j3]

In [139]:
j0

(0.5+0j) [] +
(-0.5+0j) [Z0]

In [140]:
from scipy.linalg import expm

ttt = [1j*np.pi*get_sparse_operator(op, n_qubits=4).todense() for op in q_list]

pol = reduce(lambda x,y: x+y, ttt)

exp_pol = expm(pol)
np.where(expm(exp_pol)!=0)

np.diag(exp_pol)

array([ 1.+0.j, -1.+0.j, -1.+0.j,  1.-0.j, -1.+0.j,  1.-0.j,  1.-0.j,
       -1.+0.j, -1.+0.j,  1.-0.j,  1.-0.j, -1.+0.j,  1.-0.j, -1.+0.j,
       -1.+0.j,  1.-0.j])

In [142]:
H_mat = get_sparse_operator(molecule.H).todense()

In [144]:
H_mat@exp_pol == exp_pol@H_mat

matrix([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          T

In [145]:
FermionOperator()

0

In [297]:
import os
import yaml

In [304]:
molecule.hf_array.tolist()


[1, 1, 0, 0]

In [364]:
data = {}
H_dict = molecule.H_q.to_dictionary

for key in H_dict.keys():
    H_dict[key] = float(H_dict[key].real)

# H_dict = {'cat': H_dict['IIII']}
data['H'] = H_dict
data['taper_reference'] = molecule.hf_array.tolist()

In [365]:
data

{'H': {'IIII': -0.09706626816763056,
  'IIIZ': -0.2234315369081347,
  'IIZI': -0.2234315369081347,
  'IIZZ': 0.1744128761226159,
  'IZII': 0.1714128264477691,
  'IZIZ': 0.12062523483390414,
  'IZZI': 0.1659278503377034,
  'ZIII': 0.17141282644776906,
  'ZIIZ': 0.1659278503377034,
  'ZIZI': 0.12062523483390414,
  'ZZII': 0.16868898170361205,
  'XXYY': -0.045302615503799264,
  'XYYX': 0.045302615503799264,
  'YXXY': 0.045302615503799264,
  'YYXX': -0.045302615503799264},
 'taper_reference': [1, 1, 0, 0]}

In [366]:
out = os.path.join(os.getcwd(), 'H2_JW.yaml')
with open(out, 'w') as file:
    yaml.dump(data, file)

In [367]:
with open(out, "r") as stream:
    try:
        test = yaml.full_load(stream)
    except yaml.YAMLError as exc:
        print(exc)

In [368]:
test

{'H': {'IIII': -0.09706626816763056,
  'IIIZ': -0.2234315369081347,
  'IIZI': -0.2234315369081347,
  'IIZZ': 0.1744128761226159,
  'IZII': 0.1714128264477691,
  'IZIZ': 0.12062523483390414,
  'IZZI': 0.1659278503377034,
  'XXYY': -0.045302615503799264,
  'XYYX': 0.045302615503799264,
  'YXXY': 0.045302615503799264,
  'YYXX': -0.045302615503799264,
  'ZIII': 0.17141282644776906,
  'ZIIZ': 0.1659278503377034,
  'ZIZI': 0.12062523483390414,
  'ZZII': 0.16868898170361205},
 'taper_reference': [1, 1, 0, 0]}