In [1]:
from symmer.utils import gf2_gaus_elim
from symmer.utils import random_symplectic_matrix

In [122]:
B = random_symplectic_matrix(50,100000)
B

array([[0, 1, 1, ..., 1, 1, 1],
       [0, 1, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 1, 1, ..., 0, 1, 0]])

In [12]:
%timeit gf2_gaus_elim(B)

580 µs ± 29.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [74]:
B = np.array([
    [1,1,0,0],
    [1,1,0,1],
    [0,1,1,1],
    [0,0,1,0],
    [0,0,0,1]
])

In [87]:
import numpy as np

max_i, max_j = B.shape
all_indices = np.arange(max_j)
B_copy = B.copy()
print(B_copy)

for j in range(max_j):
    try:
        pivot = np.where(B_copy[:,j])[0][0]
        update_set = np.setdiff1d(np.where(B_copy[pivot]), j)
        for k in update_set:
            B_copy[:,k] = np.bitwise_xor(B_copy[:,k], B_copy[:,j])
            print(B_copy)
    except:
        pass
        
print(B_copy)

[[0 0 0 0 1 1]
 [1 0 0 1 1 0]
 [0 1 1 1 1 1]
 [0 1 1 1 0 0]
 [1 0 0 0 0 1]
 [1 0 0 1 1 0]]
[[0 0 0 0 1 1]
 [1 0 0 0 1 0]
 [0 1 1 1 1 1]
 [0 1 1 1 0 0]
 [1 0 0 1 0 1]
 [1 0 0 0 1 0]]
[[0 0 0 0 1 1]
 [1 0 0 0 0 0]
 [0 1 1 1 1 1]
 [0 1 1 1 0 0]
 [1 0 0 1 1 1]
 [1 0 0 0 0 0]]
[[0 0 0 0 1 1]
 [1 0 0 0 0 0]
 [0 1 0 1 1 1]
 [0 1 0 1 0 0]
 [1 0 0 1 1 1]
 [1 0 0 0 0 0]]
[[0 0 0 0 1 1]
 [1 0 0 0 0 0]
 [0 1 0 0 1 1]
 [0 1 0 0 0 0]
 [1 0 0 1 1 1]
 [1 0 0 0 0 0]]
[[0 0 0 0 1 1]
 [1 0 0 0 0 0]
 [0 1 0 0 0 1]
 [0 1 0 0 1 0]
 [1 0 0 1 1 1]
 [1 0 0 0 0 0]]
[[0 0 0 0 1 1]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 1 1]
 [1 0 0 1 1 1]
 [1 0 0 0 0 0]]
[[0 0 0 0 1 1]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 1 1]
 [0 0 0 1 1 1]
 [1 0 0 0 0 0]]
[[0 0 0 0 1 1]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 1 1]
 [0 0 0 1 0 1]
 [1 0 0 0 0 0]]
[[0 0 0 0 1 1]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 1 1]
 [0 0 0 1 0 0]
 [1 0 0 0 0 0]]
[[0 0 0 0 1 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 1 0]
 [0 0 0 1 0 0]
 [1 0 0 0 0 0]]

In [123]:
import numpy as np

def gf2_reduction(B):
    """ O(N*M) Gaussian reduction over Gaussian field of binary numbers
    """
    B_copy = B.copy()
    # iterate over rows of array
    for i, row_i in enumerate(B_copy):
        # if not a row of zeros
        if np.any(row_i):
            # find the first non-zero entry of row i
            pivot = np.where(row_i)[0][0]
            # find the non-zero entries in column i
            update_set = np.setdiff1d(np.where(B_copy[:, pivot]), i)
            # XOR the rows containing non-zero entries in column i with row i
            B_copy[update_set] = np.bitwise_xor(B_copy[update_set], row_i)
    return B_copy

In [124]:
B

array([[0, 1, 1, ..., 1, 1, 1],
       [0, 1, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 1, 1, ..., 0, 1, 0]])

In [125]:
%timeit gf2_reduction(B)

3.06 s ± 55 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [126]:
%timeit gf2_gaus_elim(B)

3.67 s ± 42.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [127]:
gf2_reduction(B)

array([[0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [129]:
gf2_gaus_elim(B)

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])